---
DNORegion: B
# Permitted regions are:
# A = East England
# B = East Midlands
# C = London
# D = North Wales, Merseyside and Cheshire
# E = West Midlands
# F = North East England
# G = North West England
# P = North Scotland
# N = South and Central Scotland
# J = South East England
# H = Southern England
# K = South Wales
# L = South West England
# M = Yorkshire

DisplayType: inkyphat
# supported display types are "blinkt" or "inkyphat".

InkyPHAT:

    HighPrice: 13.5
    # at or above this price, text and graph bars turn red/yellow.
    LowSlotDuration: 2.5
    # how long (in hours) the "lowest slot" function should search for.
    # This must be between 0.5 and 6 hours in half hour increments.

Blinkt:

    Mode: agile_price
    # supported modes are "agile_price" or "hildebrand_mqtt_power"

    Brightness: 10
    # min 5, max 100. 100 is *really really bright*.

    Colours:
    # Power is for hildebrand_mqtt_power mode, price is for agile_price mode
    # Power is in W, Price is in p/kWh
    
        Level6:
            Name: Magenta
            Power: 3000
            Price: 28.0
            R: 155
            G: 0
            B: 200
    
        Level5:
            Name: Red
            Power: 1000
            Price: 17.0
            R: 255
            G: 0
            B: 0

        Level4:
            Name: Orange
            Power: 600
            Price: 13.5
            R: 255
            G: 30
            B: 0

        Level3:
            Name: Yellow
            Power: 400
            Price: 10.0
            R: 180
            G: 100
            B: 0

        Level2:
            Name: Green
            Power: 250
            Price: 5.0
            R: 0
            G: 255
            B: 0

        Level1:
            Name: Cyan
            Power: 100
            Price: 0.0
            R: 0
            G: 160
            B: 180

        Level0:
            Name: Blue
            Power: 0
            Price: -100.0
            R: 0
            G: 0
            B: 255
